export const fr = {
  nav: { home: "Accueil", menu: "Menu", about: "À Propos", gallery: "Galerie", reservations: "Réservations", contact: "Contact", reviews: "Avis" },
  hero: { tagline: "Le Meilleur Dîner d'Agadir Depuis 2000", subtitle: "Là où la tradition rencontre la saveur. Découvrez la cuisine marocaine authentique et les saveurs internationales du Chef Omar.", reserve: "Réserver une Table", viewMenu: "Voir le Menu" },
  stats: { years: "Années d'Excellence", guests: "Clients Satisfaits", menuItems: "Plats au Menu", awards: "Prix" },
  footer: { description: "Découvrez les meilleures cuisines marocaine et internationale à Agadir. Préparées avec passion par le Chef Omar avec plus de 25 ans d'expertise culinaire.", quickLinks: "Liens Rapides", hours: "Horaires", contact: "Contact", monThu: "Lun - Jeu", friSun: "Ven - Dim", rights: "Tous droits réservés." },
  common: { bookTable: "Réserver une Table", readAll: "Voir Tous les Avis", viewFullMenu: "Voir le Menu Complet", learnStory: "Découvrir Notre Histoire", callUs: "Appelez-Nous", scroll: "Défiler", bookNow: "Réserver" },
  contactPage: { title: "Prenez Contact", subtitle: "Nous serions ravis de vous entendre. Contactez-nous pour vos questions, commentaires ou demandes spéciales.", address: "Adresse", phone: "Téléphone", email: "Email", hours: "Horaires", formTitle: "Envoyez-Nous un Message", formSubtitle: "Nous répondons généralement sous 24h", name: "Nom", subject: "Sujet", message: "Message", send: "Envoyer le Message", sending: "Envoi..." },
  aboutPage: { title: "Notre Histoire", subtitle: "Depuis plus de 25 ans, le Chef Omar crée des expériences culinaires inoubliables au Blacksmith, mélangeant tradition marocaine et saveurs du monde.", values: { passion: "Passion pour la Cuisine", globe: "Inspiration Globale", heart: "Hospitalité Chaleureuse", trophy: "Engagement pour la Qualité" } },
  reviewsPage: { title: "Ce Que Disent Nos Clients", share: "Partagez Votre Expérience", feedback: "Nous apprécions vos commentaires!", yourName: "Votre Nom", rating: "Note", submit: "Soumettre", submitting: "Soumission...", leaveUs: "Laissez-nous un Avis", help: "Votre avis nous aide à nous améliorer", onGoogle: "Avis sur Google", onTripadvisor: "Avis sur Tripadvisor" },
  galleryPage: { title: "Un Voyage Visuel", subtitle: "Explorez l'atmosphère, les saveurs et les moments qui rendent The Blacksmith spécial", empty: "Pas encore de médias dans la galerie.", emptyHint: "Ajoutez des photos depuis le tableau de bord." },
  menuPage: { fromKitchen: "De Notre Cuisine", signature: "Plats Signatures", discover: "Découvrez nos plats les plus appréciés, préparés avec les meilleurs ingrédients et 25 ans d'expertise du Chef Omar." },
};
